### ISSUE TITLE
[Misc] Release thread logo

### ISSUE THREAD

**Issue by sumghai** [StupidChris/HydroTech#19]
Something I whipped up for the release thread when the time comes:

![hydrotech_logo](https://cloud.githubusercontent.com/assets/4993380/15174171/5c423d16-17b4-11e6-8c10-4588f772f775.png)

I decided against putting "RCS Autopilot" as part of the logo, in case you want to use the HydroTech branding for other projects in the future.

**Comment by ChrisViral** [comment]
Do I ever tell you that you're awesome?

**Comment by ChrisViral** [comment]
Added this along with the .png version of the flag to an Assets folder in the root of the repository. If you ever find yourself with more stuff like this, feel free to commit it directly to that folder!
